
import React from 'react'
import {Metadata} from "next"
import LoginForms from '@/components/forms/login.forms';

export const metadata: Metadata = {
  title: "Ecommerce | Login",
  description: "Generated by create next app",
};


const LoginPage = () => {
  return (
    <main className='h-full w-full flex justify-center items-center '>
      <h1>Login</h1>
      <LoginForms/>
    </main>
  )
}

export default LoginPage
